services:
  ze-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./:/opt/ze-monitor
    environment:
      - ZE_ENABLE_SYSMAN=1
    privileged: true
    cap_add:
      - CAP_DAC_READ_SEARCH # Bypass all filesystem read access checks
      - CAP_PERFMON         # Access to perf_events (vs. overloaded CAP_SYS_ADMIN)
      - CAP_SYS_PTRACE      # PTRACE_MODE_READ_REALCREDS ptrace access mode check
